image: python:2.7

pipelines:
  default:
    - step:
        caches:
          - pip
          - buildout-eggs
          - buildout-parts
        script:
          - pip install zc.buildout
          - buildout -n buildout:eggs-directory=../eggs
          - bin/py.test -k "not webdriver"

definitions:
  caches:
    buildout-eggs: ../eggs
    buildout-parts: parts

